//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {

        }

        public Table( int id, string name, string description)
        {
            GameName = name;
            GameDescription = description;
            Id = id;
        }

        public int Id { get; set; }
        public string GameName { get; set; }
        public string GameDescription { get; set; }
    }
}
